### PR TITLE
Code changes in config.go and mgmt.go to support 'enabled' setting an…

### PR DESCRIPTION
**Pull request by johnseekins**
…d code cleanup

### CODE REVIEW

**Comment by memikequinn** [comment]
@johnseekins I'm getting build errors with this one: 
```
[mquinn/ lfs-server-go] (test-pull-request)$ ./scripts/test.sh
# github.com/memikequinn/lfs-server-go
/var/folders/ml/mglgb6hs02lc1yy2_fvggzp40000gn/T/go-build762821683/github.com/memikequinn/lfs-server-go/_test/_obj_test/config.go:94: cfg.Section("Main").HasKey undefined (type *"gopkg.in/ini.v1".Section has no field or method HasKey)
FAIL	github.com/memikequinn/lfs-server-go [build failed]
```

Is there a patch order for these changes?

**Comment by johnseekins** [comment]
The order shouldn't matter. Mostly. I don't think.

That error is strange. According to https://github.com/go-ini/ini/blob/master/README.md, an ini:
```
To check if a key exists:

yes := cfg.Section("").HasKey("key name")
```

Should work just fine, but it's failing the build? Strange.

**Comment by memikequinn** [comment]
@johnseekins I merged this and updated `HasKey` with `.Key("key").String() != ""` which is what you were probably getting ay anyway.

**Comment by johnseekins** [comment]
Thanks for the merge! And it is strange that was failing for you. Although the age old "It worked for me!" response isn't very helpful, is it?

**Pull request merged**
