### PR TITLE
Should allow for running in a URL context

### PR DESCRIPTION
**Pull request by johnseekins**
(i.e. `<host>/context/mgmt` rather than only `<host>/mgmt`)

The problem is, it requires re-embedding the template changes, which, for me, hits #13

### CODE REVIEW

**Comment by memikequinn** [comment]
@johnseekins can you please take a look @ this change?

**Comment by johnseekins** [comment]
Probably bumping into pull #10 
If we remove the changes to config.ini, I bet it builds.

**Comment by johnseekins** [comment]
There. config.ini/config.go changes removed. Should work now.

**Comment by johnseekins** [comment]
I'm learning an awful lot about git. *Now* it should successfully build.

**Comment by memikequinn** [comment]
@johnseekins I was thinking about this change and couldnt the same be accomplished by running a reverse proxy in apache/nginx/whatever?

**Comment by memikequinn** [comment]
@johnseekins I tried getting this to run under a reverse proxy and it does not work without a ton of rewrites.  Two remaining issues: I'm getting a 404 for assets:

```
http://my-box:9999/mgmt/js/mgmt.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://my-box:9999/mgmt/css/primer.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

And the links are not updated: 

```
<a class="menu-item selected" href="/mgmt/objects">Objects</a>
```

Any idea how to get around this?  If not, I can take a shot too.

**Comment by johnseekins** [comment]
This looks like the kinds of problems I was running into when I would try to repackage changes in the rice files. Maybe this pull request is terrible.

**Pull request closed without merging**
